### ISSUE TITLE
Can't set custom format

### ISSUE THREAD

**Issue by HDark15** [SN-Koarashi/ig-helper#20] opened 2024-07-26 20:51 UTC
Firefox
Can't write anything after right click

**Comment by SN-Koarashi** [comment] 2024-07-26 21:53
Can you make a video to reproduce this issue?

**Comment by SN-Koarashi** [comment] 2024-07-26 22:45
Does an input box appear after right-clicking?

**Comment by SN-Koarashi** [comment] 2024-07-28 17:03
It looks like the dark theme is causing the issue, I've updated the CSS to fix it. The issue will be fixed after refreshing the local CSS file, or you can manually update the CSS file content in the extension page.

**Closed** 2024-07-28 17:24 UTC
Labels: bug
